### ISSUE TITLE
Change the disclaimer title

### ISSUE THREAD

**Issue by bksssadhikari** [THDCMustang/thdcmustang.github.io#11]
Change it to be An official website of the THDC, Mustang.

**Comment by MegaMind98** [comment]
I've changed it as per the requirements. 
https://github.com/THDCMustang/thdcmustang.github.io/commit/8eef76c8db6bc17e9dcf78cfb80e3246a7740c9c

**Comment by MegaMind98** [comment]
https://github.com/THDCMustang/thdcmustang.github.io/commit/249f6ee9ef1b0287637dd2e19decf5c929964145
